### ISSUE TITLE
1.0 Roadmap

### ISSUE THREAD

**Issue by Ch4s3** [Sorcery/sorcery#32]
I'm starting this issue to discuss our path to a 1.0 release. Please feel free to request features here and discuss areas that need improvement or bug fixes.
- [ ] OAuth / Provider test mocking (see omniauth mocking)
  - [ ] Fake successful auth call for any provider
  - [ ] Fake unsuccessful auth call for any provider
- [ ] Token auth #70 probably with something like [jwt](https://github.com/jwt/ruby-jwt)
- [x] Support usage of multiple authentications for a single user (not sure if this is already implemented)
- [ ] Support accounts without passwords (strictly external auth)
- [x] Contribution guide
- [x] Consider OmniAuth re https://github.com/NoamB/sorcery/issues/533
- [x] Issue template
- [ ] Improve docs

ported from [here](https://github.com/NoamB/sorcery/issues/787)

**Comment by nsantiago2719** [comment]
I think you need to review the `create_from(provider)` method. Because x.yz@gmail.com is the same with xyz@gmail.com but in sorcery it treats it differently.

In google's view:
x.yz@gmail.com == xyz@gmail.com

But in sorcery's view:
x.yz@gmail.com != xyz@gmail.com

A solution can be made like the others suggest before that I can filter it through my registration controller. But I think it's a little bit different know because of the `create_from(provider)` method.

**Comment by Ch4s3** [comment]
@nsantiago2719 can you file an issue for this?

**Comment by athix** [comment]
@nsantiago2719 @Ch4s3 Not all providers ignore periods, so treating them as separate emails makes sense for the most part. I'm of the same mindset of @jrochkind in [#748](https://github.com/NoamB/sorcery/issues/748) that provider specific code should probably be documented in the wiki (with examples), but left to users to implement. One of the main draws of Sorcery is that it _doesn't_ do everything for you, and lets you handle things in a way that makes sense for your application.

**Comment by Ch4s3** [comment]
I was unaware that other providers recognize '.'

**Comment by nsantiago2719** [comment]
@athix what I am referring right now is the `create_from(provider)` method for external providers. That's why it's a little bit different to the issue that I opened before.

**Comment by athix** [comment]
@Ch4s3 Looks like Microsoft, Yahoo, and Apple treat periods as separate emails, while Google and Facebook treat them as the same.

@nsantiago2719 Hmm. Can you open a new ticket on this repo where we can discuss it further? Including the specifics on what's not behaving the way you'd expect would be helpful. Thanks! :)

**Comment by kyuden** [comment]
@Ch4s3 

How about add [omniauth integration](https://github.com/NoamB/sorcery/issues/533) to 1.0 Roadmap. 

> OAuth / Provider test mocking (see omniauth mocking)
 　　Fake successful auth call for any provider
 　　Fake unsuccessful auth call for any provider

It may be able to remove this If omniauth integration is implemented.
Because we can use mocking of omniauth itself.

**Comment by Ch4s3** [comment]
@kyuden Reading that old thread, this makes sense.

**Comment by athix** [comment]
I could definitely get behind utilizing omniauth's existing infrastructure for oauth. I think we'd want to carefully considering all the possible implications first, but it would reduce the maintenance of external providers considerably.

We also should start looking at how/if we plan on dividing sorcery up into separate modules soon. It could be that we just make the code itself more independent, or we split sorcery into multiple gems. Both have strong advantages and disadvantages.

**Comment by Ch4s3** [comment]
What is your preference re: making the code itself more independent vs. splitting @athix?

**Comment by jrochkind** [comment]
you might consider making the code more independent as a first step, then to consider splitting as a second step. Since the second requires the first as a first step anyway.

**Comment by Ch4s3** [comment]
Yeah, I think that's probably how we'd approach it. Omniauth could be a good part of that.

**Comment by athix** [comment]
Going to be working towards this on my fork [athix/sorcery:1-0-0](https://github.com/athix/sorcery/tree/1-0-0)

Current objectives:
- [ ] Gain better understanding of existing codebase
  - [ ] Complete rubocop TODO
  - [ ] Get code coverage to min 90%
- [ ] Separate code into unit-tested modules
  - [ ] Core
  - [ ] Passwords
  - [ ] HTTP Basic Auth
  - [ ] External
  - [ ] Remember Me
  - [ ] Reset Password
  - [ ] Session Timeout
  - [ ] User Activation
  - [ ] Add module dependency (e.g. all require core, reset password requires password auth, login method requires either password auth or external auth)
- [ ] Replace External module code with omniauth integration

**Comment by athix** [comment]
Would anyone object to dropping support for Rails 4? With Rails 6 on the horizon, I think it would make sense to keep the code sane.

**Comment by Ch4s3** [comment]
I think that's probably reasonable

**Comment by mladenilic** [comment]
+1 for dropping support for 4.x.

**Comment by athix** [comment]
@mladenilic here's some of the old ideas for `Sorcery 1.0`. Might need some refreshing considering how long it's been, but hopefully it can give a head-start.

**Comment by athix** [comment]
This will be continued by #248, closing.
